openapi: 3.0.3
info:
  title: STD24226
  version: 1.0.0
  description: This is a specification of STD24226
servers:
  - url: https://localhost:8000

paths:
  /ping:
      get:
        responses:
          200:
            description: pong
            content:
              text/plain:
                schema:
                  type: string
                  example: pong
  /cars:
      post:
        requestBody:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/"
      responses:
        201:
          description: List of tasks created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/